#!/usr/bin/env bash
# mock-git.sh — shared PATH-injected `git` mock for the test suites.
#
# Sourced, not executed. Call write_mock_git to (re)write the mock.
#
# Why this is shared: the mock used to be hand-copied into every suite that
# needed it, and every copy delegated unmatched subcommands with
# `command git "$@"`. `command` bypasses functions and aliases but NOT PATH
# lookup, and the mock's own directory is prepended to PATH — so each copy
# re-executed itself without bound. That stayed latent until a caller ran a
# second git subcommand, then spawned 56k processes and exhausted the
# terminal's cgroup pid controller. One implementation, guarded twice:
#
#   1. Delegation strips the mock's own directory from PATH, so `exec git`
#      reaches the real binary.
#   2. A depth counter aborts on the third re-entry, so any *future*
#      delegation mistake fails loudly instead of forking forever.
#
# Usage:
#   source "$SCRIPT_DIR/../lib/mock-git.sh"
#   write_mock_git "$MOCK_DIR" "https://github.com/owner/repo.git"
#
#   # with extra cases (one `case` arm per line, matched before delegation):
#   write_mock_git "$MOCK_DIR" "https://github.com/owner/repo.git" \
#     '  "config user.name") echo "testuser" ;;'
#
# write_mock_git also installs a default `tea` stub (see write_mock_tea_login
# below) unless the caller has already written one. That is deliberate: git-wait
# resolves the platform from the remote host BEFORE it parses arguments, and on
# a non-github remote that means reading `tea login list`. A suite that mocked
# git but not tea therefore fell through to the REAL tea on PATH — passing on a
# machine with a matching login and failing in CI, where there is no tea at all.
# Bundling the stub with the git mock makes the hermetic thing the default
# instead of something each new suite has to remember.
#
# `gh` deliberately gets no equivalent: platform detection never invokes it, so
# it is only ever reached through calls the suites already mock explicitly.

# _mock_host_from_remote <remote_url>
# Mirror of git-wait's own hostname extraction, so the stub's login list is
# keyed the same way detection will look it up.
_mock_host_from_remote() {
  local url="$1"
  if [[ "$url" =~ ^ssh:// ]]; then
    echo "$url" | sed -E 's|^ssh://[^@]*@([^:/]+).*|\1|'
  elif [[ "$url" =~ ^git@ ]]; then
    echo "$url" | sed -E 's|^git@([^:]+):.*|\1|'
  elif [[ "$url" =~ ^https?:// ]]; then
    echo "$url" | sed -E 's|^https?://([^/:]+).*|\1|'
  fi
}

# write_mock_tea_login <mock_dir> [login_host_url]
# A tea whose only job is to satisfy platform detection. With a host it reports
# one login for that host (detection → gitea); with no host it reports an empty
# list (detection falls through to github, and a real tea login cannot hijack
# the result). Every other subcommand fails loudly rather than silently
# reaching the network — a suite that needs API responses writes its own mock
# over this one.
write_mock_tea_login() {
  local dir="$1" host="${2:-}" logins='[]'
  [[ -n "$host" ]] && logins="[{\"url\":\"$host\"}]"
  cat >"$dir/tea" <<EOF
#!/usr/bin/env bash
# Generated by tests/lib/mock-git.sh — do not hand-copy this file.
case "\$1 \$2 \$3" in
  "login list --output") echo '$logins'; exit 0 ;;
esac
echo "mock tea: unmocked call '\$*' — this suite must write its own tea mock into its mock dir" >&2
exit 1
EOF
  chmod +x "$dir/tea"
}

# write_mock_git <mock_dir> <remote_url> [extra_case_arms]
write_mock_git() {
  local dir="$1" remote="$2" extra="${3:-}"

  {
    cat <<'MOCK_PRELUDE'
#!/usr/bin/env bash
# Generated by tests/lib/mock-git.sh — do not hand-copy this file.
if [ "${MOCK_GIT_DEPTH:-0}" -gt 2 ]; then
  echo "mock git: recursion detected on '$*' (depth ${MOCK_GIT_DEPTH})" >&2
  exit 1
fi
export MOCK_GIT_DEPTH=$((${MOCK_GIT_DEPTH:-0} + 1))
case "$*" in
MOCK_PRELUDE

    printf '  "remote get-url origin") echo "%s" ;;\n' "$remote"
    [[ -n "$extra" ]] && printf '%s\n' "$extra"

    cat <<'MOCK_CODA'
  # Strip this mock's own directory from PATH before delegating, so `git`
  # resolves to the real binary rather than back to this script.
  *) PATH=${PATH#"${0%/*}":}; exec git "$@" ;;
esac
MOCK_CODA
  } >"$dir/git"

  chmod +x "$dir/git"

  # Install the default tea stub only when the suite has not already written
  # its own. Suites re-call write_mock_git between cases (to vary the remote or
  # a rev-parse result), and clobbering a richer tea mock on each of those calls
  # would break them.
  if [[ ! -e "$dir/tea" ]]; then
    local host
    host=$(_mock_host_from_remote "$remote")
    if [[ -n "$host" && "$host" != "github.com" ]]; then
      write_mock_tea_login "$dir" "https://$host"
    else
      write_mock_tea_login "$dir" ""
    fi
  fi
}
