#!/usr/bin/env bash
# mock-git.sh — shared PATH-injected `git` mock for the test suites.
#
# Sourced, not executed. Call write_mock_git to (re)write the mock.
#
# Why this is shared: the mock used to be hand-copied into every suite that
# needed it, and every copy delegated unmatched subcommands with
# `command git "$@"`. `command` bypasses functions and aliases but NOT PATH
# lookup, and the mock's own directory is prepended to PATH — so each copy
# re-executed itself without bound. That stayed latent until a caller ran a
# second git subcommand, then spawned 56k processes and exhausted the
# terminal's cgroup pid controller. One implementation, guarded twice:
#
#   1. Delegation strips the mock's own directory from PATH, so `exec git`
#      reaches the real binary.
#   2. A depth counter aborts on the third re-entry, so any *future*
#      delegation mistake fails loudly instead of forking forever.
#
# Usage:
#   source "$SCRIPT_DIR/../lib/mock-git.sh"
#   write_mock_git "$MOCK_DIR" "https://github.com/owner/repo.git"
#
#   # with extra cases (one `case` arm per line, matched before delegation):
#   write_mock_git "$MOCK_DIR" "https://github.com/owner/repo.git" \
#     '  "config user.name") echo "testuser" ;;'

# write_mock_git <mock_dir> <remote_url> [extra_case_arms]
write_mock_git() {
  local dir="$1" remote="$2" extra="${3:-}"

  {
    cat <<'MOCK_PRELUDE'
#!/usr/bin/env bash
# Generated by tests/lib/mock-git.sh — do not hand-copy this file.
if [ "${MOCK_GIT_DEPTH:-0}" -gt 2 ]; then
  echo "mock git: recursion detected on '$*' (depth ${MOCK_GIT_DEPTH})" >&2
  exit 1
fi
export MOCK_GIT_DEPTH=$((${MOCK_GIT_DEPTH:-0} + 1))
case "$*" in
MOCK_PRELUDE

    printf '  "remote get-url origin") echo "%s" ;;\n' "$remote"
    [[ -n "$extra" ]] && printf '%s\n' "$extra"

    cat <<'MOCK_CODA'
  # Strip this mock's own directory from PATH before delegating, so `git`
  # resolves to the real binary rather than back to this script.
  *) PATH=${PATH#"${0%/*}":}; exec git "$@" ;;
esac
MOCK_CODA
  } >"$dir/git"

  chmod +x "$dir/git"
}
